### ISSUE TITLE
Where is the models.wideresnet ?

### ISSUE THREAD

**Issue by FormerAutumn** [FPNAS/LBGAT#1]
Thanks for your great work :)

When I read your codes, I found  
`
from models.wideresnet import *
`
in
https://github.com/FPNAS/LBGAT/blob/main/auto_attack_eval.py#L11

however, there isn't any file named 'models' in this repo, so I wanna know the where can I get the wrn so that it can match the weights published in this repo.

Thanks in advance :D

**Comment by jiequancui** [comment]
Hi, we use the default model file from TRADES.  

I have updated the model files.

**Comment by FormerAutumn** [comment]
Thank you so much ! :D
So fast a reply 💯 💯 💯
