### ISSUE TITLE
I don't see any prints. How long will it take to train? What about loss curve?

### ISSUE THREAD

**Issue by headscott** [FPNAS/LBGAT#10]
Hey, I am currently training your model by executing `bash sh/train_lbgat0_cifar100.sh`. I did not see any progress prints until now. Are there even any, if so, can I make them more frequent? And how long does one train usually take on GPU Nvidia RTX 4090 for example or something kind of similar? Can I see my Loss Curve anywhere?

**Comment by jiequancui** [comment]
Hi,

Thanks for your interest in our work.
There should be training log files. Please check it.

Best,
Jiequan

**Comment by headscott** [comment]
Oh, you are right sorry. I was just blind
