### ISSUE TITLE
Why do you Evaluate at Epoch 92?

### ISSUE THREAD

**Issue by Leminhbinh0209** [FPNAS/LBGAT#8]
Hi,

I have a question that  why did you evaluate the model at epoch 91-92. As far as I know, early stopping can gain more robustness (http://proceedings.mlr.press/v119/rice20a/rice20a.pdf) but it can be only used when you have another validation set. And did you do the same for other methods?

**Comment by jiequancui** [comment]
Hi,

Thanks for your question.
We use the best model for all methods for comparisons.

Best,
